name: golang-build-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'crawl-*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    strategy:
      matrix:
        id: [a, b]
        include:
          - id: a
            os: windows-latest
            startIdx: 0
            endIdx: 2501
            targetZip: output-${{ github.ref_name }}-0-2501.zip
          - id: b
            os: windows-latest
            startIdx: 2501
            endIdx: -1
            targetZip: output-${{ github.ref_name }}-2501-end.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - shell: cmd
        run: |
          curl https://github.com/dirkarnez/batchted/releases/download/v1.0.0/batchted-v1.0.0.zip -L --output batchted-v1.0.0.zip &&^
          dir &&^
          7z.exe x batchted-v1.0.0.zip
          
      - shell: cmd
        run: |
          batchted.exe --input=2023-01-30T20-14-42+08-00.txt --start=${{ matrix.startIdx }} --end=${{ matrix.endIdx }}
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 2023-01-30T20-14-42+08-00.txt
          filename: "${{ matrix.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ matrix.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
